name: Setup Environment
description: 'Setup Node.js, pnpm, and dependencies'

inputs:
  install-playwright:
    description: 'Whether to install Playwright browsers'
    required: false
    default: 'false'
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '23'
  pnpm-version:
    description: 'pnpm version to use'
    required: false
    default: '10'

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Install Playwright Browsers
      if: ${{ inputs.install-playwright == 'true' }}
      run: pnpx playwright install --with-deps
      shell: bash
